/* ScopeAI visual polish and owner contact details. */
if (!state.phone) state.phone = '8490894316';
if (!state.email || state.email === 'aarav@medcareclinic.com') state.email = 'koshtidrgesh566@gmail.com';
localStorage.setItem('scopeai-state', JSON.stringify(state));

const polishStyle = document.createElement('style');
polishStyle.textContent = `
  body.dark .cta{background:linear-gradient(120deg,#172554,#312e81);color:#fff;border:1px solid #334155;box-shadow:0 20px 45px #02061788}body.dark .cta p{color:#c7d2fe}body.dark .footer{background:#020617;color:#cbd5e1;border-top:1px solid #1e293b}body.dark .footer a{color:#bfdbfe}body.dark .footer b{color:#fff}
  .about-shell{margin-top:24px;background:linear-gradient(140deg,#eff6ff,#faf5ff);border:1px solid #dbeafe;border-radius:22px;padding:45px;display:grid;grid-template-columns:1.2fr .8fr;gap:35px;overflow:hidden;position:relative}.about-shell:after{content:'';position:absolute;width:260px;height:260px;border-radius:50%;right:-80px;top:-100px;background:#c4b5fd55}.about-shell>*{position:relative;z-index:1}.about-stat{background:#fff;padding:17px;border-radius:14px;border:1px solid #ddd6fe}.about-stat strong{display:block;font:700 28px 'Space Grotesk';color:#3730a3}.contact-strip{margin-top:20px;padding:17px 20px;border-radius:13px;background:#0f172a;color:#fff;display:flex;justify-content:space-between;align-items:center;gap:15px;flex-wrap:wrap}.contact-strip a{color:#bfdbfe;text-decoration:none}.footer-info{display:flex;justify-content:space-between;gap:20px;align-items:flex-start;flex-wrap:wrap}.footer-meta{max-width:500px;line-height:1.7}.footer-links{display:flex;gap:16px;flex-wrap:wrap}.footer-links a{margin:0}.dash-hero{margin:22px 0;padding:26px;border-radius:18px;background:linear-gradient(115deg,#1d4ed8,#6d28d9);color:#fff;position:relative;overflow:hidden}.dash-hero:after{content:'✦';position:absolute;font-size:160px;right:24px;top:-60px;color:#fff2}.dash-hero h2,.dash-hero p{position:relative;z-index:1}.dash-hero p{color:#dbeafe;max-width:620px}.dash-hero .btn{background:#fff;color:#1d4ed8;position:relative;z-index:1}.pulse-grid{display:grid;grid-template-columns:1.2fr .8fr;gap:16px;margin-top:18px}.progress-item{padding:14px 0;border-top:1px solid var(--line)}.progress-item:first-child{border-top:0}.progress-item span{display:flex;justify-content:space-between;font-size:14px}.progress-item .bar{background:var(--line)}.accent-card{background:linear-gradient(145deg,#eff6ff,#faf5ff)}body.dark .about-shell,body.dark .accent-card{background:linear-gradient(145deg,#172554,#1e1b4b);border-color:#334155}body.dark .about-stat{background:#111827;border-color:#374151}body.dark .about-stat strong{color:#c4b5fd}@media(max-width:780px){.about-shell,.pulse-grid{grid-template-columns:1fr}.about-shell{padding:26px}.dash-hero{padding:23px}.contact-strip{align-items:flex-start}}
`;
document.head.appendChild(polishStyle);

function aboutContent() { return `<section id="about" class="section wrap"><div class="about-shell"><div><span class="eyebrow">About ScopeAI</span><h2>Discovery should feel clear, not chaotic.</h2><p class="muted">ScopeAI is a focused workspace for turning early conversations into practical project roadmaps. It brings requirements, priorities, delivery planning and team alignment into one professional brief.</p><div class="actions"><a class="btn" href="#/analyze">Start an analysis →</a><a class="btn secondary" href="#/contact">Talk to us</a></div></div><div><div class="about-stat"><strong>4 steps</strong><span class="muted">from a first idea to a shareable project brief</span></div><div class="about-stat" style="margin-top:12px"><strong>1 workspace</strong><span class="muted">for clients, agencies and project teams</span></div></div></div><div class="contact-strip"><div><b>Need help with ScopeAI?</b><br><span>Personal support for your project planning workflow.</span></div><div><a href="mailto:koshtidrgesh566@gmail.com">koshtidrgesh566@gmail.com</a> · <a href="tel:8490894316">+91 84908 94316</a></div></div></section>`; }
function richFooter() { const footer = document.querySelector('.footer'); if (!footer) return; footer.innerHTML = `<div class="wrap footer-info"><div class="footer-meta"><b>ScopeAI</b><br>Turn ideas into clear project roadmaps.<br><small>Questions or support: <a href="mailto:koshtidrgesh566@gmail.com">koshtidrgesh566@gmail.com</a> · <a href="tel:8490894316">+91 84908 94316</a></small><p>© 2026 ScopeAI. Built for agencies, startups, and product teams.</p></div><div class="footer-links"><a href="#/about">About</a><a href="#/pricing">Pricing</a><a href="#/privacy">Privacy</a><a href="#/terms">Terms</a><a href="#/contact">Contact</a><a href="#/dashboard">Dashboard</a></div></div>`; }
function addDashboardPolish() { const content = document.querySelector('.content'); if (!content || location.hash !== '#/dashboard') return; if (!content.querySelector('.dash-hero')) { const hero = document.createElement('section'); hero.className = 'dash-hero'; hero.innerHTML = `<span class="eyebrow" style="color:#bfdbfe">Your workspace</span><h2>Keep your next project moving.</h2><p>Your MedCare brief is ready for the next conversation. Review the roadmap, then share it with the team when you are ready.</p><a class="btn" href="#/brief/demo">Open latest brief →</a>`; content.querySelector('.metric-grid')?.after(hero); const pulse = document.createElement('section'); pulse.className = 'pulse-grid'; pulse.innerHTML = `<article class="panel"><h2>Workspace pulse</h2><div class="progress-item"><span><b>Brief completeness</b><b>86%</b></span><div class="bar"><i style="width:86%"></i></div></div><div class="progress-item"><span><b>Discovery readiness</b><b>72%</b></span><div class="bar"><i style="width:72%;background:#7c3aed"></i></div></div><div class="progress-item"><span><b>Team alignment</b><b>64%</b></span><div class="bar"><i style="width:64%;background:#16a34a"></i></div></div></article><article class="panel accent-card"><span class="eyebrow">Recommended next step</span><h2>Validate the booking journey</h2><p class="muted">Confirm appointment rules and reminder timing with clinic staff before design begins.</p><a class="btn secondary" href="#/dashboard/briefs">Review brief details →</a></article>`; content.append(pulse); } }
function aboutRoute() { if (location.hash !== '#/about') return; app.innerHTML = home(); requestAnimationFrame(() => document.getElementById('about')?.scrollIntoView({behavior:'smooth'})); }
function polishSettings() { if (location.hash !== '#/dashboard/settings' || document.getElementById('profilePhone')) return; const save = document.querySelector('[onclick="saveProfileDetails()"]'); if (save) save.insertAdjacentHTML('beforebegin', `<div class="field"><label for="profilePhone">Mobile number</label><input id="profilePhone" type="tel" value="${state.phone || ''}"></div>`); }
function saveProfileDetails() { state.name = document.getElementById('profileName').value.trim(); state.company = document.getElementById('profileCompany').value.trim(); state.email = document.getElementById('profileEmail').value.trim(); state.phone = document.getElementById('profilePhone')?.value.trim() || state.phone; localStorage.setItem('scopeai-state', JSON.stringify(state)); toast('Your profile and contact details have been saved.'); }
function polishPage() { const main = document.querySelector('main'); if ((location.hash === '#/' || location.hash === '#/about') && main && !main.querySelector('#about')) main.insertAdjacentHTML('beforeend', aboutContent()); const navLinks = document.querySelector('.navlinks'); if (navLinks && !navLinks.querySelector('.about-link')) { const about = document.createElement('a'); about.className='about-link'; about.href='#/about'; about.textContent='About'; navLinks.insertBefore(about, navLinks.firstChild); } richFooter(); addDashboardPolish(); polishSettings(); }
window.addEventListener('hashchange', () => { setTimeout(aboutRoute, 0); setTimeout(polishPage, 10); });
setTimeout(() => { aboutRoute(); polishPage(); }, 10);
